version: 2 # use CircleCI 2.0
jobs: 
  build: 

    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker: 
      - image: circleci/openjdk:11-stretch 
        

    steps: 

      - checkout:

      - restore_cache: 
          
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run:
           name: Deploy Master to Heroku
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/weatherapp-circleci-backend.git master
           auth:
           username: sohailkhan4764@gmail.com
           password: zcbm12342@A  # context / project UI env-var reference 

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports

      
      - store_artifacts: 
          
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar