version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker:
      - image: circleci/openjdk:11-stretch

    steps:
      - checkout:

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
