
version: 2

 jobs:
   build:
     ...
   deploy:
     docker:
       - image: circleci/openjdk:11-stretch 
         auth:
           username: sohailkhan2709@gmail.com
           password: zcbm12342@A  # context / project UI env-var reference
     steps:
       - checkout
       - run:
           name: Deploy Master to Heroku
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/weather-api-app-web.git master

 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch
      